##CREATE a dashboard

```{r}
install.packages("RSQLite")
install.packages("plotly")
```

```{r}
library(RSQLite)
library(ggplot2)
library(plotly)
library(shiny)
```

```{r}
con <- dbConnect(RSQLite::SQLite(), dbname = "database.db")

query <- "SELECT * FROM btc_price"
btc_data <- dbGetQuery(con, query)

btc_data
dbDisconnect(con)

```

Ühendus töötab, saan andmebaasist info kätte.

Teen "candlestick" graafiku BTC kohta

```{r}
btc_prices <- data.frame(
  timestamp = as.POSIXct(btc_data$timestamp, origin = "1970-01-01"),
  open = btc_data$open,
  high = btc_data$high,
  low = btc_data$low,
  close = btc_data$close,
  volume = btc_data$volume
)
btc_prices
```

```{r}
candlestick_chart <- plot_ly(data = btc_prices, type = "candlestick",
                             x = ~timestamp,
                             open = ~open,
                             high = ~high,
                             low = ~low,
                             close = ~close)
candlestick_chart
```

```{r}
#candlestick_chart <- candlestick_chart %>%
#  layout(title = "Bitcoin Candlestick Chart",
#         yaxis = list(title = "Price"),
#         xaxis = list(title = "Timestamp"))
```

```{r}
ui <- fluidPage(
  plotlyOutput("candlestickChart")
)

server <- function(input, output) {
  output$candlestickChart <- renderPlotly({
    candlestick_chart
  })
}

shinyApp(ui, server)

```
